⬆️ Update aws-cdk to v2.144.0
For some reason there was an error during `cdk synth` on the new version.
Pinned it down on having two Schedules. Since I only need one Schedule anyways I commented one out.

The error was the following:
```
Error: Resolution error: Resolution error: Resolution error: All principals in a PolicyStatement must have the same Conditions (got '{}' and '{"StringEquals":{"aws:SourceAccount":"${Token[AWS.AccountId.9]}"}}'). Use multiple statements instead..
Object creation stack:
  at stack traces disabled..
    at PolicyStatement.addPrincipalConditions (/home/manuel/git/carbon-aware-serverless-jobs/node_modules/aws-cdk-lib/aws-iam/lib/policy-statement.js:2:7201)
    at PolicyStatement.addPrincipals (/home/manuel/git/carbon-aware-serverless-jobs/node_modules/aws-cdk-lib/aws-iam/lib/policy-statement.js:2:2407)
    at new PolicyStatement (/home/manuel/git/carbon-aware-serverless-jobs/node_modules/aws-cdk-lib/aws-iam/lib/policy-statement.js:2:663)
    at PolicyStatement.copy (/home/manuel/git/carbon-aware-serverless-jobs/node_modules/aws-cdk-lib/aws-iam/lib/policy-statement.js:2:6086)
    at mergeIfCombinable (/home/manuel/git/carbon-aware-serverless-jobs/node_modules/aws-cdk-lib/aws-iam/lib/private/merge-statements.js:1:1847)
    at onePass (/home/manuel/git/carbon-aware-serverless-jobs/node_modules/aws-cdk-lib/aws-iam/lib/private/merge-statements.js:1:1032)
    at mergeStatements (/home/manuel/git/carbon-aware-serverless-jobs/node_modules/aws-cdk-lib/aws-iam/lib/private/merge-statements.js:1:660)
    at PolicyDocument._maybeMergeStatements (/home/manuel/git/carbon-aware-serverless-jobs/node_modules/aws-cdk-lib/aws-iam/lib/policy-document.js:1:3033)
    at PolicyDocument.resolve (/home/manuel/git/carbon-aware-serverless-jobs/node_modules/aws-cdk-lib/aws-iam/lib/policy-document.js:1:1755)
    at RememberingTokenResolver.resolveToken (/home/manuel/git/carbon-aware-serverless-jobs/node_modules/aws-cdk-lib/core/lib/resolvable.js:1:1401)
```