⬇️ Downgrade cdk to a previous version
With 2.99.1 a cdk diff produces following error:
y cdk diff
yarn run v1.22.19
warning ../../../package.json: No license field
$ cdk diff
Error: Cannot find module './aspect'
Require stack:
- node_modules/aws-cdk-lib/core/lib/index.js
- node_modules/aws-cdk-lib/core/index.js
- node_modules/aws-cdk-lib/lazy-index.js
- CarbonAwareServerlessJobs.ts